### ISSUE TITLE
iOS Debug Log output

### ISSUE THREAD

**Issue by BenVanCitters** [jacobdufault/fullserializer#61] opened 2015-08-03 16:45 UTC
I added FullSerializer to an existing Unity 4.6.5 project and after compiling to iOS devices I started seeing Full-Serializer output from stack trace in Unity's Debug.Log calls:

```
Transition to state InitializationState (UnityEngine.GameObject)  <<< ---- Debug.Log() Output
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
XXXXXXX.AwardsManager:ParseJSON()
XXXXXXX.AwardsManager:Init()
XXXXXXX.AwardsManager:Load()
InvocationLib.OperationList:get_Exception()
<LoadModules>c__Iterator1B:MoveNext()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
GlobalModules:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)
```

The FullSerializer output doesn't show in the simulator/in Unity only in Xcode when running on a device.  This is the cause of some concern.  Do you know what is causing this output, and/or how it can be removed?

**Comment by jacobdufault** [comment] 2015-08-04 04:16
Is this with il2cpp? Unfortunately I don't have an actual iOS device, only the simulator.

- If you're on il2cpp, can you please verify you have the latest version.

- ```InvocationLib.OperationList:get_Exception()
<LoadModules>c__Iterator1B:MoveNext()```

Maybe something is going wrong with the type selection reflection. Can you try removing [these](https://github.com/jacobdufault/fullserializer/blob/master/Source/Reflection/fsTypeLookup.cs#L21-L31) lines?

**Comment by BenVanCitters** [comment] 2015-08-04 22:07
Just to be clear, we aren't getting any sort of crash - not all of the traces contain the 'get_Exception()' part.  Either way, removing the code you suggested doesn't remove the FullSerializer output from the stack.

We are on il2cpp and we have tried using the latest version to no effect.

Why is FullSerializer.fsDirectConverter.TryDeserialize() getting called so frequently?

**Comment by jacobdufault** [comment] 2015-08-11 05:19
I'm not sure why these messages are appearing. There should not be any log messages in FI. If you ever find an actual error please let me know - for now these are hopefully harmless.

**Comment by jacobdufault** [comment] 2015-08-11 05:21
```
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
XXXXXXX.AwardsManager:ParseJSON()
XXXXXXX.AwardsManager:Init()
XXXXXXX.AwardsManager:Load()
```

Is there a log statement inside of AwardsManager.ParseJSON? Can you share the code for that function?

**Comment by BenVanCitters** [comment] 2015-08-19 17:55
Hey, sorry for the long silence!  I don't think ParseJSON() has anything specific to do with the log output.  Here is a much more complete log from xcode.  As you can see very single call to Debug.Log anywhere in our codebase produces output characteristic of the above. 

Unfortunately, I can't share 100% of the code or log right now.  Let me know how I can help more.

-> applicationDidBecomeActive()

Requesting Resolution: 1334x750
Init: screen size 1334x750
Initializing Metal device caps
2015-08-08 15:22:59.118 Sonicare4Kids-Smiggles[1043:679890] localArray :(
"en_US"
)
Initialize engine version: 4.6.5f1 (c2bb1d7d067c)
WARNING: Shader Unsupported: 'Reflective/VertexLit' - Pass 'BASE' shader state not supported
thingXXX
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
S4KApplication:Awake()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

Transition to state InitializationState (UnityEngine.GameObject)
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
ApplicationFlow.Manager:QueueTransitionTo(State, TransitionStyle)
StartApplicationFlow:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

Awards loaded from JSON.
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.AwardsManager:ParseJSON()
xxxxxxx.XXXXXX.xxxxxxxx.AwardsManager:Init()
xxxxxxx.XXXXXX.xxxxxxxx.AwardsManager:Load()
InvocationLib.OperationList:get_Exception()
<LoadModules>c__Iterator1B:MoveNext()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
GlobalModules:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

Data request from unity of type MusicStatus
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataManager:RequestData(ApplicationData, Action`1)
xxxxxxx.XXXXXX.xxxxxxxx.SoundStatusManager:Init()
xxxxxxx.XXXXXX.xxxxxxxx.SoundStatusManager:Load()
InvocationLib.OperationList:get_Exception()
<LoadModules>c__Iterator1B:MoveNext()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
GlobalModules:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

Data request from unity of type SoundEffectStatus
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataManager:RequestData(ApplicationData, Action`1)
xxxxxxx.XXXXXX.xxxxxxxx.SoundStatusManager:Init()
xxxxxxx.XXXXXX.xxxxxxxx.SoundStatusManager:Load()
InvocationLib.OperationList:get_Exception()
<LoadModules>c__Iterator1B:MoveNext()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
GlobalModules:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

Data request from unity of type xxxxxxx
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataManager:RequestData(ApplicationData, Action`1)
xxxxxxx.XXXXXX.xxxxxxxx.SleepCycleManager:Load()
InvocationLib.OperationList:get_Exception()
<LoadModules>c__Iterator1B:MoveNext()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
GlobalModules:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

TestSupportManager init
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.TestSupportManager:Init()
xxxxxxx.XXXXXX.xxxxxxxx.TestSupportManager:Load()
InvocationLib.OperationList:get_Exception()
<LoadModules>c__Iterator1B:MoveNext()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
GlobalModules:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

DataReceiver1 - MusicStatus
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataReceiver:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

DataReceiver2 - SoundEffectStatus
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataReceiver:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

DataReceiver3 - xxxxxxxx
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataReceiver:Start()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

======> Debug mode enabled.
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.MonoBehaviour:print(Object)
<OnStateReadyAsync>c__Iterator1D:MoveNext()
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

Received command from native : UpdateSuspendUnity
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataManager:ReceivedNativeCommand(ApplicationCommand)
ReceivedNativeCommand:Invoke(ApplicationCommand)
xxxxxxx.XXXXXX.xxxxxxxx.HabitatController:Unload()
InterApp:Command(String)
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

aaaa
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataManager:ReceivedNativeCommand(ApplicationCommand)
ReceivedNativeCommand:Invoke(ApplicationCommand)
xxxxxxx.XXXXXX.xxxxxxxx.HabitatController:Unload()
InterApp:Command(String)
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

Data request from unity of type UnitySuspendStatus
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
xxxxxxx.XXXXXX.xxxxxxxx.DataManager:RequestData(ApplicationData, Action`1)
xxxxxxx.XXXXXX.xxxxxxxx.DataManager:ReceivedNativeCommand(ApplicationCommand)
ReceivedNativeCommand:Invoke(ApplicationCommand)
xxxxxxx.XXXXXX.xxxxxxxx.HabitatController:Unload()
InterApp:Command(String)
FullSerializer.fsDirectConverter`1:TryDeserialize(fsData, Object&, Type)

(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7-il2cppGenerated/UnityEngineDebug.cpp Line: 56)

**Comment by jacobdufault** [comment] 2016-06-11 17:17
Closing since I can't reproduce and the stack traces don't lead to much. I'm guessing a memory corruption issue on Unity's side.

**Closed by jacobdufault** 2016-06-11 17:17 UTC
